name: Backend CI

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
    runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for Postgres
        run: sleep 10

        env:
          SPRING_PROFILES_ACTIVE: dev
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: admin

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test -Dspring.profiles.active=dev

      - name: Build Docker image
        run: docker build -t ged-backend .

